// <auto-generated />
using System;
using LexoraED.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LexoraED.Migrations
{
    [DbContext(typeof(LexoraEDContext))]
    partial class LexoraEDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LexoraED.Models.Learner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Learners");
                });

            modelBuilder.Entity("LexoraED.Models.LearningAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttemptDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int");

                    b.Property<int>("QuizSetId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId");

                    b.HasIndex("QuizSetId");

                    b.ToTable("LearningAttempts");
                });

            modelBuilder.Entity("LexoraED.Models.LearningModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("LearningModules");
                });

            modelBuilder.Entity("LexoraED.Models.LearningProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompletedModulesCount")
                        .HasColumnType("int");

                    b.Property<string>("CurrentLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId")
                        .IsUnique();

                    b.ToTable("LearningProgresses");
                });

            modelBuilder.Entity("LexoraED.Models.QuizItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChoiceA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChoiceB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChoiceC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChoiceD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("QuizSetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizSetId");

                    b.ToTable("QuizItems");
                });

            modelBuilder.Entity("LexoraED.Models.QuizSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LearningModuleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LearningModuleId");

                    b.ToTable("QuizSets");
                });

            modelBuilder.Entity("LexoraED.Models.LearningAttempt", b =>
                {
                    b.HasOne("LexoraED.Models.Learner", "Learner")
                        .WithMany("LearningAttempts")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LexoraED.Models.QuizSet", "QuizSet")
                        .WithMany("LearningAttempts")
                        .HasForeignKey("QuizSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("QuizSet");
                });

            modelBuilder.Entity("LexoraED.Models.LearningProgress", b =>
                {
                    b.HasOne("LexoraED.Models.Learner", "Learner")
                        .WithOne("LearningProgress")
                        .HasForeignKey("LexoraED.Models.LearningProgress", "LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("LexoraED.Models.QuizItem", b =>
                {
                    b.HasOne("LexoraED.Models.QuizSet", "QuizSet")
                        .WithMany("QuizItems")
                        .HasForeignKey("QuizSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizSet");
                });

            modelBuilder.Entity("LexoraED.Models.QuizSet", b =>
                {
                    b.HasOne("LexoraED.Models.LearningModule", "LearningModule")
                        .WithMany("QuizSets")
                        .HasForeignKey("LearningModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningModule");
                });

            modelBuilder.Entity("LexoraED.Models.Learner", b =>
                {
                    b.Navigation("LearningAttempts");

                    b.Navigation("LearningProgress");
                });

            modelBuilder.Entity("LexoraED.Models.LearningModule", b =>
                {
                    b.Navigation("QuizSets");
                });

            modelBuilder.Entity("LexoraED.Models.QuizSet", b =>
                {
                    b.Navigation("LearningAttempts");

                    b.Navigation("QuizItems");
                });
#pragma warning restore 612, 618
        }
    }
}
